import * as XLSX from "xlsx";
import saveAs from "file-saver";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ColumnInfo, Row } from "./analytics";
import { fmtNum } from "./analytics";

export function exportExcel(rows: Row[], filename = "report.xlsx") {
  const ws = XLSX.utils.json_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Data");
  XLSX.writeFile(wb, filename);
}

export function exportCSV(rows: Row[], filename = "report.csv") {
  const ws = XLSX.utils.json_to_sheet(rows);
  const csv = XLSX.utils.sheet_to_csv(ws);
  saveAs(new Blob([csv], { type: "text/csv;charset=utf-8" }), filename);
}

export function exportPDF(opts: {
  title: string;
  columns: ColumnInfo[];
  rows: Row[];
  filename?: string;
}) {
  const { title, columns, rows, filename = "report.pdf" } = opts;
  const doc = new jsPDF({ orientation: "landscape" });

  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42);
  doc.text(title, 14, 18);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by Sheetly • ${new Date().toLocaleString()}`, 14, 25);

  // Summary section
  const numericCols = columns.filter((c) => c.type === "number");
  const summary = numericCols.map((c) => [
    c.name, fmtNum(c.sum), fmtNum(c.avg), fmtNum(c.min), fmtNum(c.max), String(c.missing),
  ]);

  autoTable(doc, {
    startY: 32,
    head: [["Column", "Sum", "Avg", "Min", "Max", "Missing"]],
    body: summary.length ? summary : [["No numeric columns detected", "", "", "", "", ""]],
    headStyles: { fillColor: [99, 102, 241] },
    styles: { fontSize: 9 },
  });

  // Data preview (first 30 rows)
  const previewRows = rows.slice(0, 30);
  const keys = columns.map((c) => c.name);
  const body = previewRows.map((r) => keys.map((k) => String(r[k] ?? "")));

  // @ts-ignore - autotable adds lastAutoTable
  const startY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text(`Data Preview (showing ${previewRows.length} of ${rows.length} rows)`, 14, startY);
  autoTable(doc, {
    startY: startY + 4,
    head: [keys],
    body,
    headStyles: { fillColor: [139, 92, 246] },
    styles: { fontSize: 8, cellPadding: 2 },
  });

  doc.save(filename);
}
